### ISSUE TITLE
Can we convert zip shp to OSM?

### ISSUE THREAD

**Issue by Laudarisd** [roelderickx/ogr2osm#12]
Hello @roelderickx Thanks for the nice repository.
I have a question.
I have a shp zip file which contains multiple shp files with other files like prj, shx.
Can I convert this zip file to OSM without loosing any information?

Is it possible?
If I can then can you give me some hint such?

Thank you

**Comment by roelderickx** [comment]
Yes this is possible, just pass the zipfile in stead of the decompressed shapefile as the argument to ogr2osm. Ogr2osm will create one outputfile containing all geometries found in all shapefiles in the zip archive.
Note that you can specify a projection or input encoding, but this applies to all files in the zip archive. If one of the files is different from the others you need to decompress and write a small shell script to get everything processed correctly.

**Comment by Laudarisd** [comment]
Thank you for your reply. Sorry couldn't reply on time. I was able to convert zip to osm but nodes shp files didn't convert properly. When I tried to upload in neteditor it says that nodes are not available. 
Any idea ?
Thank you so much.

**Comment by roelderickx** [comment]
I am not sure neteditor is capable of opening osm files. Do you see the nodes in JOSM? Does the problem persists when unzipping first and converting the individual files?

**Comment by Laudarisd** [comment]
I tried to convert individually, still problem exists.
I tried to open file in blender.
Except node file everything looks okay.
Thank you

**Comment by roelderickx** [comment]
Interesting. Can I download a sample file somewhere to test?

**Comment by Laudarisd** [comment]
If I get your email id then I could send you the node file.

**Comment by roelderickx** [comment]
@Laudarisd Did you receive my mail?

**Comment by Laudarisd** [comment]
@roelderickx Didn't receive.

**Comment by roelderickx** [comment]
Please send it to ogr2osm.pypi@derickx.be

**Comment by Laudarisd** [comment]
Thanks, I have sent you an email. Hoping for your help.

**Comment by roelderickx** [comment]
I have tried converting the shapefile, it appears to work as designed. The file contains all the nodes:
```
<node visible="true" id="-1" lat="37.585419198" lon="126.885083272"><tag k="nodeid" v="7253"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-2" lat="37.586888316" lon="126.886959997"><tag k="nodeid" v="7254"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-3" lat="37.585945097" lon="126.885673841"><tag k="nodeid" v="7360"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-4" lat="37.585680507" lon="126.885427647"><tag k="nodeid" v="7390"/><tag k="nodetype" v=""/></node>
```
and they are visible in JOSM as well:
![image](https://user-images.githubusercontent.com/33570192/127679698-f50ae3ee-be82-47b0-975d-cda7cf893a32.png)

However, as you can see, the `nodetype` tag is empty. Do you expect them to have a value? Where should the data come from?

**Comment by roelderickx** [comment]
I have tried converting the shapefile, it appears to work as designed. The file contains all the nodes:
```
<node visible="true" id="-1" lat="36.595419198" lon="125.875083272"><tag k="nodeid" v="8569"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-2" lat="36.596888316" lon="125.876959997"><tag k="nodeid" v="8541"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-3" lat="36.595945097" lon="125.875673841"><tag k="nodeid" v="8579"/><tag k="nodetype" v=""/></node>
<node visible="true" id="-4" lat="36.595680507" lon="125.875427647"><tag k="nodeid" v="8580"/><tag k="nodetype" v=""/></node>
```
The nodes are visible in JOSM as well.

However, as you can see, the `nodetype` tag is empty. Do you expect them to have a value? Where should the data come from?
