### ISSUE TITLE
Can we convert SHP to opendrive format?

### ISSUE THREAD

**Issue by Laudarisd** [roelderickx/ogr2osm#13]
One more question?

I need opendrive format from shp files. 
Instead of openstreet format, can I change it in to opendrive format directly ?

Any suggestions? 

Thank you.

**Comment by roelderickx** [comment]
I should have a look to the opendrive format to give you a definitive answer, but it may be possible if you are willing to write some python code.
Start with the example code to [use ogr2osm as a library](https://github.com/roelderickx/ogr2osm#as-a-library) and instantiate the datawriter as a user-defined subclass of ogr2osm.DataWriterBase. It should be rather straightforward to implement.
However, writing opendrive files is not the main goal of ogr2osm so this will not be implemented in this repository.

**Comment by Laudarisd** [comment]
Sorry for late reply and than you for your time and answer. I will give a try to make an opendrive file.
