### ISSUE TITLE
no official equivalent of --id available when using ogr2osm as a library

### ISSUE THREAD

**Issue by pnoll1** [roelderickx/ogr2osm#23]
When switching from cli to library usage, I noticed there's no equivalent of the --id option mentioned in the example code. I managed to get the same behavior using

    ogr2osm.osm_geometries.OsmId.set_id(id) 

before defining the data source. You may want to add this or a cleaner version to the example

**Comment by roelderickx** [comment]
Thanks for your report.

I've overlooked the combination of setting an id and the use of ogr2osm as a library, but that's of course a legit use. What you did is the only way for now but I agree it doesn't feel as the most elegant solution.

I think it would be more appropriate to set the start id in the instance of the `OsmData` class. I'll add it in the course of this week to the github repository.

**Comment by roelderickx** [comment]
The OsmData constructor has two new optional parameters now: start_id and is_positive. Only start_id is documented, is_positive is the equivalent of the equally undocumented --positive-id parameter.

**Comment by pnoll1** [comment]
Looks good to me

**Comment by roelderickx** [comment]
I added two more functions `load_start_id_from_file` and `save_current_id_to_file` to OsmData implementing the --idfile and --saveid, to avoid the use of the OsmId class in client applications.
New testcases are added and all tests pass, merging into main and closing this issue. A new package release will follow shortly.
