### ISSUE TITLE
Issue with ids when converting a shp into osm

### ISSUE THREAD

**Issue by DACNC** [roelderickx/ogr2osm#24]
When converting a shapefile into osm format, the id values from the shapefile are not kept in the output.
Could it be possible to update the ogr2osm code to allow the user to keep the value of a specific column from the input data as osm_id value?

Thanks in advance

**Comment by roelderickx** [comment]
The data in shapefiles and OSM files do not correspond 1:1, there are no id values to copy over. However, there may be a solution for your requirement using a translation file, see pnorman/ogr2osm#57.
