### ISSUE TITLE
Returning None from filter_layer in translation throws error

### ISSUE THREAD

**Issue by kinimesi** [roelderickx/ogr2osm#31]
According to the docs, `filter_layer` can return a layer or `None`. However, returning `None` throws the following error:
```
ogr2osm/ogr2osm/ogr_datasource.py", line 101, in __get_source_reprojection_func
    layer_spatial_ref = layer.GetSpatialRef()
AttributeError: 'NoneType' object has no attribute 'GetSpatialRef'
```

Looking into the original library, seems like there was a [check](https://github.com/pnorman/ogr2osm/blob/a20f3310c9e81c8231f3c2109cb93db9adc72931/ogr2osm.py#L229) for `None`, but it got lost during refactoring.

**Comment by roelderickx** [comment]
Good catch!
The original check is still in the refactored code: https://github.com/roelderickx/ogr2osm/blob/70d2f04e0761ca98b294703bb965d39d667d9295/ogr2osm/osm_data.py#L418

But that code is only executed after we tried to fetch the projection, which is of course impossible for an empty layer.
I'll merge the pull request.
