### ISSUE TITLE
Possibility to export a regional cut from a postgresql db created by osm2pgsql

### ISSUE THREAD

**Issue by tumluliu** [roelderickx/ogr2osm#34]
Hi @roelderickx , thanks a lot for making and continuously improving this handy tool. I am facing such a use case that I need to export a specific bbox-defined regional portion from a PG database created via an importing of `planet.osm.pbf` with osm2pgsql. It's pretty much like what Geofabrik or BBBike does behind the scene. So I'm wondering if it's possible to do such a job with this awesome tool by only providing a translation file. Could you provide some insights or suggestions? Thank you!

**Comment by roelderickx** [comment]
Hi @tumluliu 
I have done this before, please have a look at the contour-osm project: https://github.com/roelderickx/contour-osm

In case the input is a file you need the functionality in the `filter_layer` translation method, but in case the input is stored in a postgresql / postgis database it is even easier: you can adapt the query to calculate the intersection using postgis.

For example how I extracted the elevation lines (the `geom` column) per height (the `height` column) from the table `elevation` for only limited area:
```
select height, ST_Intersection(geom, p.polyline)
from (select ST_GeomFromText('MULTIPOLYGON (((6.051 50.5191 0,6.1232 50.5191 0,6.1232 50.4792 0,6.051 50.4792 0,6.051 50.5191 0)))', 4326)  polyline) p, elevation
where ST_Intersects(geom, p.polyline)
```

Note that you're not limited to rectangle areas, you can use the poly files from geofabrik. Have a look at the `Polyfile` class in contour-osm to get an idea how to do this, you just have to convert the files to WKT format to be able to use it in the query.

**Comment by tumluliu** [comment]
Thanks for your quick reply @roelderickx ! I will take a closer look at the contour-osm project, and give it a try with your hints.
