### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by pnoll1** [roelderickx/ogr2osm#35]
I'm at a point where certain data sources are filling ram until they are stopped by the OOM killer. I see that this has been an ongoing issue: pnorman/ogr2osm#36. My use case is slightly different since I'm only using nodes(address data).

The problem data source is originally 6.6 GB of uncompressed geojson data. When trying to write that data from Postgres to pbf, memory usage goes to 56GB(+7GB going to swap I think) and the process is killed before anything is written. Only log from ogr2osm is projection metadata:

`2023-04-28 17:20:52,790 ogr2osm INFO Detected projection metadata:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AXIS["Latitude",NORTH],
    AXIS["Longitude",EAST],
    AUTHORITY["EPSG","4326"]]`

It seems abnormal that ogr2osm needs 8x+ the uncompressed file size to process the data. Everything I'm working with is open source so I can provide code, data, logs etc.

**Comment by roelderickx** [comment]
Hi @pnoll1 
I did a few tests and at first sight it seems that ogr2osm consumes more memory when given a geojson file compared to the same data in for example a shapefile. I need testing with a larger dataset to back this claim though.
If confirmed it would mean the geojson driver of the GDAL package is somehow to blame, but converting your data to another format using `ogr2ogr` is not a solution I'd consider acceptable. It may however be an option if you are able to adapt your toolchain to have the data available in another format.
You could also try with the `--no-memory-copy` parameter. I don't expect the problem to be resolved but it will free up at least some memory.

**Comment by pnoll1** [comment]
I'm using ogr2osm to write from Postgres to pbf. I've already converted the original file from geojson to postgres using ogr2ogr.

**Comment by pnoll1** [comment]
I ran the code with more logging and memory spike is happening during osmdata.process(datasource) call.  I halted the program and got this stack trace:


```
  File "/home/pat/projects/osmand_map_creation/osmand_osm/osm/./processing.py", line 137, in pg2osm
    osmdata.process(datasource)
  File "/usr/local/lib/python3.11/dist-packages/ogr2osm/osm_data.py", line 422, in process
    self.add_feature(ogrfeature, layer_fields, datasource.source_encoding, reproject)
  File "/usr/local/lib/python3.11/dist-packages/ogr2osm/osm_data.py", line 373, in add_feature
    for osmgeometry in [ geom for geom in osmgeometries if geom ]:
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ogr2osm/osm_data.py", line 373, in <listcomp>
    for osmgeometry in [ geom for geom in osmgeometries if geom ]:
```

There's a comment above this call: # TODO performance: run in __parse_geometry to avoid second loop.

**Comment by roelderickx** [comment]
Apparently I was looking in the wrong place yesterday. It seems the `[ geom for geom in osmgeometries if geom ]` construct is creating a copy of the list, which is logical if you think about it. That's fine for the example lists in the python documentation, but not for osmgeometries.

I am not sure anymore why I didn't include the call to `translation.process_feature_post` in `__parse_geometry`. Probably because it involves adding lots of parameters to all the parse functions, all the way to the deepest levels.

Since you are probably not using the `process_feature_post` translation method you can simply disable the loop entirely and see if the memory problem is resolved. If you need the translation method then creating a copy can be avoided like this:
```
for osmgeometry in osmgeometries:
    if osmgeometry:
        self.translation.process_feature_post(osmgeometry, ogrfilteredfeature, ogrgeometry)
```

**Comment by pnoll1** [comment]
Unfortunately, I can't validate the fix right now. It turns out that I I'm trying to process double the data I should be(52 million nodes) due to a bug in my code or upstream.

I'll make some time tomorrow to try out the fix, probably on a different data set.

**Comment by pnoll1** [comment]
I tried testing the 2 proposed fixes and baseline with a 390k node source and didn't see a difference in peak memory usage(measured using scalene). Each run was nearly identical to this:
```
       │Time   │–––––– │–––––– │Memory  │–––––– │–––––––––––    │Copy   │                                                                                                                                                                                                                  
  Line │Python │native │system │Python  │peak   │timeline/%     │(MB/s) │./processing.py                                                                                                                                                                                                   
╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
   ... │       │       │       │        │       │               │       │                                                                                                                                                                                                                  
   131 │       │       │       │  25%   │   10M │▁   2%         │       │    datasource.open_datasource("PG:dbname={0}".format(db_name))                                                                                                                                                   
   ... │       │       │       │        │       │               │       │                                                                                                                                                                                                                  
   135 │       │       │       │  82%   │  524M │▁▂▃▃▄▅▅▆▇  83% │    17 │    osmdata.process(datasource)                                                                                                                                                                                   
   ... │       │       │       │        │       │               │       │                                                                                                                                                                                                                  
   140 │       │       │       │  51%   │   19M │▁▁  11%        │    16 │        osmdata.output(datawriter)                                                                                                                                                                                
   ... │       │       │       │        │       │               │       │                                                                                                                                                                                                                  
       ╵       ╵       ╵       ╵        ╵       ╵               ╵       ╵                     \
```
The code also cycles through that block a lot(each node?) so it may be chance I halted while that was running.  It looks like the problem is on my end. Thanks for taking a look.

**Comment by roelderickx** [comment]
Ok, thanks for the investigation you have done. A critical view is always good.
