### ISSUE TITLE
processes getting killed with big geojson files 

### ISSUE THREAD

**Issue by DeepakSharda** [roelderickx/ogr2osm#50]
We are trying to convert huge geojson files to osm somewhere like 15 gb. process is getting killed. the server size is 32 core 125 gb ubuntu 22.04.  just before the library starts to write data into the osm file .  Works fine for same data with smaller section.

**Comment by DeepakSharda** [comment]
Thanks for the reply.  i was monitoring it closely and found that it was
not the cpu issue it  ran out of memory. I created a swap memory of 64 gb
on top of 125 and still got killed. Running again with 125 swap memory.

**Comment by DeepakSharda** [comment]
Ok the swap memory of 125 gb get me through it .  Solved

**Comment by roelderickx** [comment]
Good to hear that, thanks for the confirmation.
